### ISSUE TITLE
Documentation: Docker Support

### ISSUE THREAD

**Issue by digital-dann** [gleeds/cloudbbq#19]
After some fiddling, I found a way to build a Docker container for this. Docker my preferred way to run this, even on a Raspberry Pi. Some people might find this useful, too:

Dockerfile
```
FROM node:10-buster

RUN git clone https://github.com/gleeds/cloudbbq.git \
  && cd cloudbbq \
  && npm install

COPY docker-entrypoint.sh /entrypoint.sh

RUN chmod u+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

docker-entrypoint.sh
```
#!/bin/sh

cd /cloudbbq
exec npm start
```

docker-compose.yml
```
version: '3'
services:
  cloudbqq:
    container_name: cloudbbq
    image: cloudbbq:latest
    network_mode: host
    volumes:
      - ./default.json:/cloudbbq/config/default.json
    restart: unless-stopped
```
